version: "3.1"
services:
  web:
    image: iamfrisbee/wordpress:6.2
    environment:
      # sets the database name
      - MYSQL_DATABASE=wordpress
      # sets the database user name
      - MYSQL_USER=wordpress
      # sets the database password
      - MYSQL_PASSWORD=changeme
      # sets the apache port
      - PORT=8000
      # sets the wordpress table prefix
      - PREFIX=wp_
      # sets the login to admin and password to change for the user with id of 1
      #- RESET_ADMIN=1
    volumes:
      - ./source/themes:/var/www/html/wp-content/themes
      - ./source/plugins:/var/www/html/wp-content/plugins
      - ./source/uploads:/var/www/html/wp-content/uploads
      - ./source/db:/src/db
      - ./source/data:/var/lib/mysql
    ports:
      - "8000:8000"
